# Generated by Django 4.1.2 on 2022-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AddField(
            model_name='photo',
            name='extension',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
