# Generated by Django 4.1.2 on 2022-10-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_alter_photo_options_photo_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
