# Generated by Django 4.1.2 on 2022-10-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_photo_unique_title_album_combination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='photo',
            name='unique_title_album_combination',
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('title', 'url')},
        ),
    ]
